version: "3.7"

services:
  parkwhere:
    container_name: parkwhere
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./index.js:/usr/src/app/index.js
      - ./.env:/usr/src/app/.env
      - ./db:/usr/src/app/db

  parkwhere-cron:
    container_name: parkwhere-cron
    build: ./cron
    restart: always
    volumes:
      - ./cron/cron.py:/app/src/cron.py