version: "3.7"

services:
  timpark:
    container_name: timpark
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./index.js:/usr/src/app/index.js
      - ./db:/usr/src/app/db